deploy lagi

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,22 +37,11 @@ jobs:
               echo "Repository already exists. Checking remote configuration..."
               cd /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/
 
-              # Check if remote 'origin' exists
-              if git remote get-url origin > /dev/null 2>&1; then
-                echo "Remote 'origin' exists. Pulling latest changes..."
-              else
-                echo "Remote 'origin' not found. Setting it up..."
-                git remote add origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/muhzhen/hannah-course.git
-              fi
-
-              # Configure credentials
+              # Configure Git to use the PAT for authentication
               git config --global credential.helper store
-              echo "https://$GITHUB_ACTOR:${{ secrets.PERSONAL_ACCESS_TOKEN }}" > ~/.git-credentials
+              echo "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic" > ~/.git-credentials
+
+              # Pull the latest changes
+              git config pull.rebase false
+              git pull origin main || { echo "Failed to pull from remote repository"; exit 1; }
             fi
-
-            # Change to the application directory and pull changes
-            cd /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/
-            git config pull.rebase false
-
-            # Pull the latest changes
-            git pull origin main || { echo "Failed to pull from remote repository"; exit 1; }
